### ISSUE TITLE
Make this plugin official?

### ISSUE THREAD

**Issue by recliq** [XertroV/tm-list-players-pbs#2]
Hi,

since the last Trackmania/Openplanet update (Fall 2024) it's no longer possible to use this very nice plugin, since School and Developer modes are prohibited on most online servers (disconnect).
Is there any way to get this plugin into the officially supported plugins?

Best regrards 
recliq

**Comment by XertroV** [comment]
Hey, so yes, but it will be nerfed a bit for ranked since toxicity there is the main concern.

**Comment by recliq** [comment]
Hey,

thanks for the quick response, I get that and I think most users (I know) wouldn't mind if it doesn't work atall in ranked... if that is even possible. It was just nice to have this plugin when hunting with fellow players in a room.

**Comment by XertroV** [comment]
I've submitted an updated version for review, now. Might take a little while to get through review b/c Miss is sick but hopefully soon.

**Comment by recliq** [comment]
Thank you!

**Comment by XertroV** [comment]
Released! You can download it from the plugin manager now.
